ORG 0000h
	AJMP MAIN;ajmp absolute jump 
	ORG 0013H
	CLR P0.0;Turn ON LED
HERE:	JNB P3.3,HERE;CHECKINH THE STATUS OF SWITCH
	SETB P0.0;TURN OFF LED
	RETI;used to end an interupt service routine
	ORG 30h
MAIN:	SETB P0.3
	CLR P0.0;P0.0 OUTPUT
	SETB P0.1
	SETB TCON.2;TCON means timer control
	MOV IE,#10000100b;INT 1 ENABLE
WAIT:	SJMP WAIT
	END
